export const Texts = {
  "pt-BR": {
    details: "Detalhes",
    address: "Endereço",
    email: "Email",
    links: "Links",
    profile: "Perfil",
    experience: "Experiências",
    out: "Out 2021",
    ago: "Ago 2021",
    feb: "Fev 2022",
    jan: "Jan 2022",
    mar: "Mar 2022",
    jul: "Jul 2022",
    apr: "Abr 2022",
    http: "HTTP: Entendendo a web por baixo dos panos",
    "html-1": "HTML5 e CSS3 parte 1: crie uma página da Web",
    jun: "Jun 2021",
    "html-2": "HTML5 e CSS3 parte 2: posicionamento, listas e navegação",
    "html-3": "HTML5 e CSS3 parte 3: trabalhando com formulários e tabelas",
    sass: "Sass: O CSS com superpoderes",
    git: "Git e Github: controle e compartilhe seu código",
    chrome: "Chrome DevTools: analise, inspecione e depure suas páginas Web",
    javascript: "JavaScript: programando a Orientação a Objetos",
    "type-1": "TypeScript parte 1: evoluindo seu JavaScript",
    "angular-1": "Angular: boas práticas em arquiteturas e formulários",
    "angular-2": "Angular: testes automatizados com Jasmine e Karma",
    "angular-3": "Angular: explorando o framework",
    spring: "pring Boot API REST: construa uma API",
    "java-1": "Java OO: entendendo a Orientação a Objetos",
    "java-2": "Java Polimorfismo: entenda herança e interfaces",
    "java-3": "Java JRE e JDK: compile e execute o seu programa",
    "java-4": "Java Exceções: aprenda a criar, lançar e controlar exceções",
    "react-1": "React: entendendo como a biblioteca funciona",
    "react-2": "React: lidando com arquivos estáticos",
    "react-3": "React: escrevendo com Typescript",
    "react-4": "React: gerenciamento de estados globais com ContextAPI",
    "react-5": "React: otimizando a performance",
    "react-6": "React: integrando seu projeto React com APIs",
    "react-7": "React: conhecendo a biblioteca React Router",
    bootstrap: "Bootstrap 4: criando uma landing page responsiva",
    position: "Desenvolvedora Front-End",
    city: "João Pessoa - PB",
    country: "Brasil",
    portuguese: "Português",
    english: "Inglês",
    "unit-tests": "Testes unitários",
    "profile-description":
      "Três anos de experiência como desenvolvedora front-end, especialista em design, instalação, teste e manutenção de sistemas de software. Capaz de autogerenciar com eficácia durante projetos independentes, bem como colaborar como parte de uma equipe produtiva.",
    "experience-description":
      "Implementei e atualizei aplicações web utilizando habilidades de programação de alto nível usando JavaScript, Typescript, React e Angular. Utilizando Karma e Jasmine para testes unitários na aplicação Angular e Testing Library e Jest na aplicação React.",
    remote: "Trabalho remoto",
    period: "Maio, 2021 - Presente",
    "education-title-1": "Bacharelado, Engenharia Civil",
    "education-title-2": "Pós-graduação, Arquitetura de Software",
    "education-period-1": "Jan 2011 - Dez 2015",
    "education-period-2": "Mar 2023 - Out 2023",
  },
  en: {
    details: "Details",
    address: "Address",
    email: "Email",
    links: "Links",
    profile: "Profile",
    experience: "Employment history",
    out: "Oct 2021",
    ago: "Aug 2021",
    feb: "Feb 2022",
    jan: "Jan 2022",
    mar: "Mar 2022",
    jul: "Jul 2022",
    apr: "Apr 2022",
    http: "HTTP: Understanding the web behind the scenes",
    "html-1": "HTML5 and CSS3 part 1: The first web page",
    jun: "Jun 2021",
    "html-2": "HTML5 and CSS3 part 2: Positioning, lists and navigation",
    "html-3": "HTML5 and CSS3 part 3: Working with forms and tables",
    sass: "Sass: CSS with superpowers",
    git: "Git and Github: Control and share your code",
    chrome: "Chrome DevTools: analyze, inspect and debug your web pages",
    javascript: "JavaScript: programando a Orientação a Objetos",
    "type-1": "TypeScript part 1: Evolving your JavaScript",
    "angular-1": "Angular: Best practices in architectures and forms",
    "angular-2": "Angular: Automated tests with Jasmine and Karma",
    "angular-3": "Angular: Starting with the Framework",
    spring: "Spring Boot API REST: Build an API",
    "java-1": "Java OO: Introduction to Object Orientation",
    "java-2": "Java Polymorphism: Understand heritance and interfaces",
    "java-3": "Java Exceptions: Learn to Create, Throw, and Handle Exceptions",
    "java-4": "Java Exceções: aprenda a criar, lançar e controlar exceções",
    "react-1": "React: Understanding how Libraries Works",
    "react-2": "React: Dealing with Static Files",
    "react-3": "React Fundamentals: Writing with Typescript",
    "react-4": "React: Global State Management with Context API",
    "react-5": "React: Optimizing Performance",
    "react-6": "React: Integrating your React project with APIs",
    "react-7": "React: conhecendo a biblioteca React Router",
    bootstrap: "Bootstrap 4: Creating a Responsive Landing Page",
    portuguese: "Portuguese",
    english: "English",
    city: "João Pessoa - PB",
    country: "Brasil",
    position: "Front-end Developer",
    "unit-tests": "Unit tests",
    "profile-description":
      "Three years experienced front-end developer adept in bringing expertise in design, installation, testing and maintenance of software systems. Able to effectively self-manage during independent projects, as well as collaborate as part of a productive team.",
    "experience-description":
      "Implemented and updated web applications utilizing high level programming skills using JavaScript, Typescript, React and Angular. Using Karma and Jasmine for unit tests in Angular application and Testing Library and Jest in React application.",
    remote: "Remote job",
    period: "May, 2021 - Present",
    "education-title-1": "Bachelor’s degree, Civil Engineering",
    "education-title-2": "Postgraduate degree, Software Architecture",
    "education-period-1": "Jan 2011 - Dec 2015",
    "education-period-2": "Mar 2023 - Oct 2023",
  },
};
